# Generated by Django 3.0.5 on 2020-04-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompetitionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_invite', to='competition.CompetitionUser')),
                ('to_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_invite', to='competition.CompetitionUser')),
            ],
        ),
    ]
